spring.application.name=backendComping

spring.data.mongodb.uri=mongodb://localhost:27017/Comping
spring.data.mongodb.database=Comping
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
spring.devtools.restart.enabled=false



server.port=8087


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ahmetchaouch19@gmail.com
spring.mail.password=iyrj aypl kggw khbo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

spring.mail.properties.mail.debug=true

logging.level.tn.comping.spring.backendcomping=DEBUG
logging.level.org.springframework.security=DEBUG

# Stripe (récupère ces clés sur https://dashboard.stripe.com/test/apikeys)
stripe.secret.key=sk_test_51TUSnN3S7emEMZrqne89DpBboAM2VHUwVS6ICPRf2oKsT9EzLmh7CX4E8aGlMBNWC5ozGyuwPnoCMBE2ruipbGIh00aNHJKBZz
