FROM node:20-alpine AS build
WORKDIR /app
COPY frontendComping/frontendCompingApp/package*.json ./
RUN npm install --legacy-peer-deps
COPY frontendComping/frontendCompingApp/ .
CMD ["npm", "start", "--", "--host", "0.0.0.0", "--port", "4200", "--disable-host-check"]
