spring.application.name=backendComping

spring.mongodb.uri=mongodb://localhost:27017/Comping
spring.mongodb.database=Comping
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG




server.port=8087


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ahmetchaouch19@gmail.com
spring.mail.password=iyrj aypl kggw khbo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000

logging.level.tn.comping.spring.backendcomping=DEBUG
logging.level.org.springframework.security=DEBUG

# Cloudinary
cloudinary.cloud.name=dyeyeeb49
cloudinary.api.key=666697511622323
cloudinary.api.secret=*********************************


# ml FASTAPI
# URL de l'API FastAPI (port 5000)
ia.api.url=http://localhost:5000/predict

# D�lai d'attente pour l'appel � FastAPI (en millisecondes)
ia.api.timeout=5000