FROM node:20-alpine AS build

WORKDIR /app

COPY frontendCompingApp/package*.json ./
RUN npm install

COPY frontendCompingApp/ ./

RUN npx ng build frontendCompingApp --configuration production

FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=build /app/dist/frontend-comping-app /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]